### ISSUE TITLE
OAuthException

### ISSUE THREAD

**Issue by ericharlow** [achvaicer/slidetagram#12]
I get a error when trying to use slidetagram.  {"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered redirect URI"}.

Would you help with this?
What do I need to configure or change?

**Comment by achvaicer** [comment]
Did you cloned it in another server?

If you did this, you need to create a new ˜client˜.
https://www.instagram.com/developer/clients/register/

Then you will receive a new client id, that you will need to change 
https://github.com/achvaicer/slidetagram/blob/gh-pages/index.html#L67

And register your domain as redirect URL on your client.

But it`s not easy to be approved anymore by Instagram as a client.

**Comment by ericharlow** [comment]
Thanks for the info.
